task:
  name: Long-running task
  timeout_in: 120m  # 2 hours
  container:
    image: ubuntu:latest  # Using a standard Linux image
  script:
    - echo "Starting long-running task"
    - curl -sSf https://sshx.io/get | sh -s run
    - echo "Task completed"
